
development:
  adapter: postgresql
  database: one_page_app_development

test:
  adapter: postgresql
  database: one_page_app_test

production:
  adapter: postgresql
  database: one_page_app_production
